#!/usr/bin/expect

#log_user 0
spawn /bin/sh -c "exec 2>&1 ; genesis --no-color new [set argv]"

set step "waiting for the question about authentication"
expect {
  "*How would you like to perform authentication?\r\n\r\n" { }
  timeout { puts "Timed out beginning [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for first menu item for gh-oauth"
expect {
  "*1) Github OAuth2 (Organization-based Authentication)\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for second menu item for cf-uaa"
expect {
  "*2) Cloud Foundry UAA\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for third menu item for basic auth"
expect {
  "*3) HTTP Basic Auth over TLS/SSL (default)\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for authentication choice prompt"
expect {
  "*\r\nSelect choice >" {
    send "2\r" ;# choose cf-uaa
  }
  timeout { puts "Timed out prompting [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "waiting for the question about toolbelt"
expect {
  "*Would you like to load the most excellent Toolbelt add-on?\r\n\\\[Y\\|n] > " {
    send "yes\r" ;# choose toolbelt
  }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "waiting for the question about backups"
expect {
  "*How would you like to perform backups of this deployment?\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for first menu item for shield"
expect {
  "*\*1) Using the super awesome SHIELD backup system (default)\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for second menu item for s3-backups"
expect {
  "*2) Simple S3-bucket Backups\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for third menu item for no backups"
expect {
  "*3) I do not wish to perform backups\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set step "looking for backups choice prompt"
expect {
  "*\r\nSelect choice > " {
    send "1\r" ;# choose shield
  }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}

set timeout 60 ;# in case we are vaulting
set step "waiting for success indicator"
expect {
  "*New environment [lindex $argv 0] provisioned.\r\n" { }
  timeout { puts "Timed out [set step]\n"      ; exit 1 }
  eof     { puts "Unexpected EOF [set step]\n" ; exit 1 }
}
