#!/bin/bash
set -eu

dir="$GENESIS_ROOT"
name="$GENESIS_ENVIRONMENT"
prefix="$GENESIS_VAULT_PREFIX"

ymlfile="$dir/$name.yml"

cat >"$ymlfile" -- <<EOF
---
kit:
  name:    $GENESIS_KIT_NAME
  version: $GENESIS_KIT_VERSION
  features:
    - (( replace ))
    - bonus

params:
  env:   $name
  vault: $prefix

  static: junk
EOF
exit 0
