#!/usr/bin/env bash
set -eu

dir="$GENESIS_ROOT"
name="$GENESIS_ENVIRONMENT"

ymlfile="$dir/$name.yml"

cat >"$ymlfile" -- <<EOF
---
kit:
  name:    $GENESIS_KIT_NAME
  version: $GENESIS_KIT_VERSION
  features:
    - (( replace ))
    - bonus
EOF

genesis_config_block >> "$ymlfile"
cat >>"$ymlfile" -- <<EOF
params:
  static: junk
EOF
exit 0
