#!/bin/bash

#
# ci/scripts/shipit
#
# Script for generating Github release / tag assets
# and managing release notes for a software pipeline
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

auto_sed() {
  file=$1
  shift
  cmd=$1
  shift

  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -E -i='' -e "$cmd" ${file}
  else
    sed -r -i -e "$cmd" ${file}
  fi
}

set -eu

if [[ -z ${VERSION_FROM} ]]; then
  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
  exit 2
fi
if [[ ! -f ${VERSION_FROM} ]]; then
  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
  exit 2
fi
VERSION=$(cat ${VERSION_FROM})
if [[ -z ${VERSION} ]]; then
  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
  exit 2
fi

pushd $REPO_ROOT
auto_sed Dockerfile "s/GENESIS_VERSION=.*/GENESIS_VERSION=${VERSION}/"
popd

# GIT!
if [[ -z $(git config --global user.email) ]]; then
  git config --global user.email "genesis-ci@rubidiumstudios.com"
fi
if [[ -z $(git config --global user.name) ]]; then
  git config --global user.name "Genesis CI Bot"
fi

(cd ${REPO_ROOT}
 git stash
 git merge --no-edit ${BRANCH}
 git stash pop
 git add -A
 git status
 git commit -m "Update docker-image with release v${VERSION}")

# so that future steps in the pipeline can push our changes
cp -a ${REPO_ROOT} ${REPO_OUT}/git
