#!/usr/bin/env bash
set -eu

export REPO_ROOT=git
export CI_ROOT=git-ci

header() {
	echo
	echo "================================================================================"
	echo "$1"
	echo "--------------------------------------------------------------------------------"
	echo
}

bail() {
	echo >&2 "$*  Did you misconfigure Concourse?"
	exit 2
}
######
header "Running tests"
pushd ${REPO_ROOT}
	make test
popd

echo
echo "--------------------------------------------------------------------------------"
echo "SUCCESS"
exit 0
