---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.ops.scalecf.net/genesis-community/genesis-ci

inputs:
  - name: git-ci

params:
  VAULT_URI:   ((vault.url))
  VAULT_TOKEN: ((vault.token))

run:
  path: git-ci/ci/scripts/renew-vault-token


