---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((docker.genesis-ci-image-path))

inputs:
  - name: git-ci

params:
  VAULT_URI:   ((vault.url))
  VAULT_TOKEN: ((vault.token))

run:
  path: git-ci/ci/scripts/renew-vault-token


