platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/genesis-ci
    tag:        latest

inputs:
  - name: git
  - name: git-ci

params:
  REPO_ROOT: git
  CI_ROOT: git-ci
  GITHUB_USER: ((github.username))
  GITHUB_AUTH_TOKEN:  ((github.access_token))

run:
  path: "git/ci/scripts/test"
  args: []
