#!/usr/bin/env bash

# The point of this script is to exit 0 if all
# required bits of functionality are present on
# the system - i.e. version checks, OS capabilities,
# (internet connectivity?)
#
# However, since this is a test, we're going to
# conditionally exit 0/non-zero based on the env var
# `$SHOULD_FAIL`.  ¯\_(ツ)_/¯

set -e
test -z "$SHOULD_FAIL"
