#!/bin/bash
shopt -so noclobber

set | grep GENESIS_
if [[ -z "${GENESIS_KIT_NAME}" \
   || -z "${GENESIS_KIT_VERSION}" \
   || -z "${GENESIS_ENVIRONMENT_NAME}" \
   || -z "${GENESIS_ENVIRONMENT_FILE}" \
   || -z "${GENESIS_VAULT_PREFIX}" \
]]; then
  echo >&2 "This script should not be called directly."
  exit 2
fi


(echo "---"
 echo "kit:"
 echo "  name:    $GENESIS_KIT_NAME"
 echo "  version: $GENESIS_KIT_VERSION"

 if [[ $# -eq 0 ]]; then
   echo "  subkits: []"
 else
   echo "  subkits:"
   for subkit in "$@"; do
     echo "    - $subkit"
   done
  fi
  echo
  echo "params:"
  echo "  env:   $GENESIS_ENVIRONMENT_NAME"
  echo "  vault: $GENESIS_VAULT_PREFIX"
  echo
) > $GENESIS_ENVIRONMENT_FILE
