#!/usr/bin/env bash
set -eu

ymlfile="$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml"

cat >"$ymlfile" -- <<EOF
---
kit:
  name:     $GENESIS_KIT_NAME
  version:  $GENESIS_KIT_VERSION
  features:
    - (( replace ))
EOF

certs_b=
prompt_for certs_b boolean \
	"Generate all the certificates?"
if [[ $certs_b == "true" ]] ; then
	echo "    - certs-b" >> "$ymlfile"
fi

genesis_config_block >> "$ymlfile"

base_domain=''
prompt_for base_domain line \
	"What is your base domain?"

cat >>"$ymlfile" -- <<EOF
params:
  base_domain: $base_domain

EOF
exit 0
