FROM starkandwayne/concourse

RUN apt-get install -yy libexpect-perl expect libtest-differences-perl

RUN git config --global user.name "Concourse BOT"
RUN git config --global user.email concourse-bot@starkandwayne.com
