---
meta:
  name:    genesis
  release: Genesis
  target:  pipes/genesis
  url:     https://pipes.scalecf.net

  initial_version: 2.9.0

  # we build our own image in this pipeline, and
  # use it, instead of standard concourse images.
  aws:
    access_key:   ((cloudfoundry-community-aws.access_key_id))
    secret_key:   ((cloudfoundry-community-aws.secret_access_key))

  git:
    name:         Genesis CI Bot
    email:        genesis-ci@rubidiumstudios.com

  vault:
    url:          ((vault.url))
    token:        ((vault.token))

  github:
    owner:        genesis-community
    repo:         genesis
    branch:       v3.0.x-dev
    main-branch:  main
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  image-registry:
    host:         "registry.ops.scalecf.net/"
    email:        ((docker.email))
    username:     ((docker.username))
    password:     ((docker.password))

  dockerhub:
    email:        ((dockerhub.email))
    username:     ((dockerhub.username))
    password:     ((dockerhub.password))

  image:
    ci-local:     ((docker.genesis-ci-image-path))
    ci-remote:    ((dockerhub.genesis-ci-image-path))
    rel-local:    ((docker.genesis-image-path))
    rel-remote:   ((dockerhub.genesis-image-path))
    rel-tag:      ((docker.genesis-image-tag))
    src:          ubuntu
    src-tag:      jammy

  shout:
    url:          ((shout.url))
    username:     ((shout.username))
    password:     ((shout.password))

