---
meta:
  name: genesis
  target: sw
  url: https://ci.vsphere.starkandwayne.com

  aws:
    access_key: (( vault "secret/pipelines/genesis/aws:access_key" ))
    secret_key: (( vault "secret/pipelines/genesis/aws:secret_key" ))

  github:
    owner: starkandwayne
    repo:  genesis
    private_key:  (( vault "secret/pipelines/genesis/github:private" ))
    access_token: (( vault "secret/pipelines/genesis/github:access_token" ))
  slack:
    webhook: (( vault "secret/pipelines/genesis/slack:webhook" ))
    channel: "#genesis"

  dockerhub:
    email: (( vault "secret/pipelines/genesis/dockerhub:email" ))
    username: (( vault "secret/pipelines/genesis/dockerhub:username" ))
    password: (( vault "secret/pipelines/genesis/dockerhub:password" ))
    repository: starkandwayne/genesis

groups:
- name: (( grab meta.pipeline ))
  jobs:
  - (( append ))
  - genesis-docker-image
jobs:
- (( append ))
- name: genesis-docker-image
  public: true
  serial: true
  plan:
  - aggregate:
    - { get: version, passed: [shipit] }
    - { get: git, passed: [shipit] }
    - { get: github, passed: [shipit], trigger: true }
  - task: update-docker-genesis
    config:
      image: (( grab meta.image ))
      platform: linux
      inputs:
      - name: version
      - name: git
      outputs:
      - name: pushme
      run:
        path: "git/ci/scripts/bump-docker-image"
        args: []
      params:
        REPO_ROOT: git
        VERSION_FROM: version/number
        REPO_OUT: pushme
        BRANCH: (( grab meta.github.branch ))
  - put: git
    params:
      rebase: true
      repository: pushme/git
  - put: genesis-image
    params:
      build: pushme/git
      tag: version/number
      tag_as_latest: true

resources:
  - name: genesis-image
    type: docker-image
    source:
      email: (( grab meta.dockerhub.email ))
      username: (( grab meta.dockerhub.username ))
      password: (( grab meta.dockerhub.password ))
      repository: (( grab meta.dockerhub.repository ))
