---
meta:
  name:    genesis
  release: Genesis
  target:  pipes/genesis
  url:     https://pipes.scalecf.com

  initial_version: 2.8.10

  # we build our own image in this pipeline, and
  # use it, instead of standard concourse images.
  image:
    name: starkandwayne/genesis_ci

  aws:
    endpoint:    ((aws.endpoint))
    access_key:  ((aws.access_key_id))
    secret_key:  ((aws.secret_access_key))
    insecure:    true
    region_name: ~

  git:
    name:  Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  vault:
    url:       ((vault.url))
    token:     ((vault.token))

  github:
    owner:        genesis-community
    repo:         genesis
    branch:       v2.8.x-dev
    main-branch:  main
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  dockerhub:
    email:    ((docker.email))
    username: ((docker.username))
    password: ((docker.password))
    repository: starkandwayne/genesis

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))

