---
meta:
  name: genesis
  target: sw

  aws:
    access_key: (( vault "secret/pipelines/genesis/aws:access_key" ))
    secret_key: (( vault "secret/pipelines/genesis/aws:secret_key" ))

  github:
    owner: starkandwayne
    repo:  genesis
    private_key:  (( vault "secret/pipelines/genesis/github:private" ))
    access_token: (( vault "secret/pipelines/genesis/github:access_token" ))
  slack:
    webhook: FIXME
    channel: "#genesis"

  dockerhub:
    email: (( vault "secret/pipelines/genesis/dockerhub:email" ))
    username: (( vault "secret/pipelines/genesis/dockerhub:username" ))
    password: (( vault "secret/pipelines/genesis/dockerhub:password" ))
    repository: starkandwayne/genesis

jobs:
  - name: shipit
    plan:
      - (( append ))
      - put: genesis-image
        params:
          build: pushme/git
          tag: version/number
          tag_as_latest: true

resources:
  - name: genesis-image
    type: docker-image
    source:
      email: (( grab meta.dockerhub.email ))
      username: (( grab meta.dockerhub.username ))
      password: (( grab meta.dockerhub.password ))
      repository: (( grab meta.dockerhub.repository ))
