---
groups:
  - jobs:
      - notify-preprod-cf-changes
      - preprod-cf
      - sandbox-cf
    name: test-pipeline
jobs:
  - name: notify-preprod-cf-changes
    plan:
      - in_parallel:
          - get: preprod-changes
            trigger:
              true
          - get: preprod-cache
            trigger:
              true
          - get: git
            passed:
              - sandbox-cf
            trigger:
              false
          - get: preprod-cloud-config
            trigger:
              true
          - get: preprod-runtime-config
            trigger:
              true
      - config:
          image_resource:
            source:
              repository: genesiscommunity/concourse
              tag: latest
            type: registry-image
          inputs:
            - name: preprod-changes
            - name: preprod-cache
            - name: git
          outputs:
            - name: out
          params:
            BOSH_NON_INTERACTIVE: "true"
            CACHE_DIR: preprod-cache
            CI_NO_REDACT: 0
            CURRENT_ENV: us-west-preprod
            GENESIS_HONOR_ENV: 1
            GIT_AUTHOR_EMAIL: "concourse@pipeline"
            GIT_AUTHOR_NAME: "Concourse Bot"
            GIT_BRANCH: main
            GIT_PRIVATE_KEY: "((git/private-key))"
            OUT_DIR: out/git
            PREVIOUS_ENV: us-west-sandbox
            VAULT_ADDR: "https://vault.example.com"
            VAULT_ROLE_ID: "((vault/role-id))"
            VAULT_SECRET_ID: "((vault/secret-id))"
            WORKING_DIR: preprod-changes
          platform: linux
          run:
            args:
              - ci-show-changes
            path: git/.genesis/bin/genesis
        task: show-pending-changes
      - in_parallel:
          - params:
              channel: "#ci"
              icon_url: ~
              text: "test-pipeline: Changes staged for us-west-preprod-cf"
              username: runwaybot
            put: slack
    public:
      true
    serial:
      true
  - name: preprod-cf
    plan:
      - do:
          - in_parallel:
              - get: preprod-changes
                passed:
                  - notify-preprod-cf-changes
                trigger:
                  false
              - get: preprod-cache
                trigger:
                  false
              - get: git
                passed:
                  - notify-preprod-cf-changes
                trigger:
                  false
          - config:
              image_resource:
                source:
                  repository: genesiscommunity/concourse
                  tag: latest
                type: registry-image
              inputs:
                - name: preprod-changes
                - name: preprod-cache
                - name: git
              outputs:
                - name: out
              params:
                BOSH_NON_INTERACTIVE: "true"
                CACHE_DIR: preprod-cache
                CI_NO_REDACT: 0
                CURRENT_ENV: us-west-preprod
                GENESIS_HONOR_ENV: 1
                GIT_AUTHOR_EMAIL: "concourse@pipeline"
                GIT_AUTHOR_NAME: "Concourse Bot"
                GIT_BRANCH: main
                GIT_PRIVATE_KEY: "((git/private-key))"
                OUT_DIR: out/git
                PREVIOUS_ENV: us-west-sandbox
                VAULT_ADDR: "https://vault.example.com"
                VAULT_ROLE_ID: "((vault/role-id))"
                VAULT_SECRET_ID: "((vault/secret-id))"
                WORKING_DIR: preprod-changes
              platform: linux
              run:
                args:
                  - ci-pipeline-deploy
                path: git/.genesis/bin/genesis
            ensure:
              params:
                repository: out/git
              put: git
            task: bosh-deploy
          - config:
              image_resource:
                source:
                  repository: genesiscommunity/concourse
                  tag: latest
                type: registry-image
              inputs:
                - name: out
                - name: git
              outputs:
                - name: cache-out
              params:
                CACHE_DIR: out/git
                CI_NO_REDACT: 0
                CURRENT_ENV: us-west-preprod
                GENESIS_HONOR_ENV: 1
                GIT_AUTHOR_EMAIL: "concourse@pipeline"
                GIT_AUTHOR_NAME: "Concourse Bot"
                GIT_BRANCH: main
                GIT_PRIVATE_KEY: "((git/private-key))"
                OUT_DIR: cache-out/git
                PREVIOUS_ENV: us-west-sandbox
                WORKING_DIR: out/git
              platform: linux
              run:
                args:
                  - ci-generate-cache
                path: git/.genesis/bin/genesis
            task: generate-cache
          - params:
              repository: cache-out/git
            put: git
        on_failure:
          in_parallel:
            - params:
                channel: "#ci"
                icon_url: ~
                text: "test-pipeline: Deployment to us-west-preprod-cf failed"
                username: runwaybot
              put: slack
        on_success:
          in_parallel:
            - params:
                channel: "#ci"
                icon_url: ~
                text: "test-pipeline: Successfully deployed us-west-preprod-cf"
                username: runwaybot
              put: slack
    public:
      true
    serial:
      true
  - name: sandbox-cf
    plan:
      - do:
          - in_parallel:
              - get: sandbox-cloud-config
                trigger:
                  true
              - get: sandbox-runtime-config
                trigger:
                  true
              - get: sandbox-changes
                trigger:
                  true
          - config:
              image_resource:
                source:
                  repository: genesiscommunity/concourse
                  tag: latest
                type: registry-image
              inputs:
                - name: sandbox-changes
                - name: git
              outputs:
                - name: out
              params:
                BOSH_NON_INTERACTIVE: "true"
                CACHE_DIR: sandbox-cache
                CI_NO_REDACT: 0
                CURRENT_ENV: us-west-sandbox
                GENESIS_HONOR_ENV: 1
                GIT_AUTHOR_EMAIL: "concourse@pipeline"
                GIT_AUTHOR_NAME: "Concourse Bot"
                GIT_BRANCH: main
                GIT_PRIVATE_KEY: "((git/private-key))"
                OUT_DIR: out/git
                PREVIOUS_ENV: "~"
                VAULT_ADDR: "https://vault.example.com"
                VAULT_ROLE_ID: "((vault/role-id))"
                VAULT_SECRET_ID: "((vault/secret-id))"
                WORKING_DIR: sandbox-changes
              platform: linux
              run:
                args:
                  - ci-pipeline-deploy
                path: git/.genesis/bin/genesis
            ensure:
              params:
                repository: out/git
              put: git
            task: bosh-deploy
          - config:
              image_resource:
                source:
                  repository: genesiscommunity/concourse
                  tag: latest
                type: registry-image
              inputs:
                - name: out
                - name: git
              outputs:
                - name: cache-out
              params:
                CI_NO_REDACT: 0
                CURRENT_ENV: us-west-sandbox
                GENESIS_HONOR_ENV: 1
                GIT_AUTHOR_EMAIL: "concourse@pipeline"
                GIT_AUTHOR_NAME: "Concourse Bot"
                GIT_BRANCH: main
                GIT_PRIVATE_KEY: "((git/private-key))"
                OUT_DIR: cache-out/git
                WORKING_DIR: out/git
              platform: linux
              run:
                args:
                  - ci-generate-cache
                path: git/.genesis/bin/genesis
            task: generate-cache
          - params:
              repository: cache-out/git
            put: git
          - get: preprod-cache
        on_failure:
          in_parallel:
            - params:
                channel: "#ci"
                icon_url: ~
                text: "test-pipeline: Deployment to us-west-sandbox-cf failed"
                username: runwaybot
              put: slack
        on_success:
          in_parallel:
            - params:
                channel: "#ci"
                icon_url: ~
                text: "test-pipeline: Successfully deployed us-west-sandbox-cf"
                username: runwaybot
              put: slack
    public:
      true
    serial:
      true
resource_types:
  - name: script
    source:
      repository: cfcommunity/script-resource
    type: registry-image
  - name: email
    source:
      repository: pcfseceng/email-resource
    type: registry-image
  - name: slack-notification
    source:
      repository: cfcommunity/slack-notification-resource
    type: registry-image
  - name: bosh-config
    source:
      repository: cfcommunity/bosh-config-resource
    type: registry-image
  - name: locker
    source:
      repository: cfcommunity/locker-resource
    type: registry-image
resources:
  - icon: github
    name: git
    source:
      branch: main
      private_key: "((git/private-key))"
      uri: "git@github.com:myorg/cf-deployments.git"
    type: git
  - icon: slack
    name: slack
    source:
      url: "((slack/webhook))"
    type: slack-notification
  - icon: github
    name: preprod-changes
    source:
      branch: main
      paths:
        - us-west-preprod.yml
      private_key: "((git/private-key))"
      uri: "git@github.com:myorg/cf-deployments.git"
    type: git
  - icon: github
    name: preprod-cache
    source:
      branch: main
      paths:
        - .genesis/cached/us-west-sandbox/us.yml
        - .genesis/cached/us-west-sandbox/us-west.yml
        - ".genesis/cached/us-west-sandbox/ops/*"
        - .genesis/cached/us-west-sandbox/kit-overrides.yml
      private_key: "((git/private-key))"
      uri: "git@github.com:myorg/cf-deployments.git"
    type: git
  - icon: script-text
    name: preprod-cloud-config
    source:
      all: 1
      ca_cert: "((bosh/preprod/ca))"
      client: admin
      client_secret: "((bosh/preprod/secret))"
      config: cloud
      target: "https://bosh.preprod:25555"
    type: bosh-config
  - icon: script-text
    name: preprod-runtime-config
    source:
      all: 1
      ca_cert: "((bosh/preprod/ca))"
      client: admin
      client_secret: "((bosh/preprod/secret))"
      config: runtime
      target: "https://bosh.preprod:25555"
    type: bosh-config
  - icon: github
    name: sandbox-changes
    source:
      branch: main
      paths:
        - us.yml
        - us-west.yml
        - us-west-sandbox.yml
        - "ops/*"
        - kit-overrides.yml
      private_key: "((git/private-key))"
      uri: "git@github.com:myorg/cf-deployments.git"
    type: git
  - icon: script-text
    name: sandbox-cloud-config
    source:
      all: 1
      ca_cert: "((bosh/sandbox/ca))"
      client: admin
      client_secret: "((bosh/sandbox/secret))"
      config: cloud
      target: "https://bosh.sandbox:25555"
    type: bosh-config
  - icon: script-text
    name: sandbox-runtime-config
    source:
      all: 1
      ca_cert: "((bosh/sandbox/ca))"
      client: admin
      client_secret: "((bosh/sandbox/secret))"
      config: runtime
      target: "https://bosh.sandbox:25555"
    type: bosh-config
