# TODO: docker-image push is insecure, so we must convert to registry-image.
#       However, registry-image push doesn't build, so an additional build task
#       is needed It is recommended by concourse to use oci-build-image, but
#       another system might work better.  See
#       https://github.com/concourse/registry-image-resource#comparison-to-docker-image-resource
#       and https://github.com/concourse/oci-build-task#oci-build-task
#

groups:
- name: generate-ci-image
  jobs:
  - genesis-ci-docker-image
jobs:
- name: genesis-ci-docker-image
  plan:
  - get: dockerfile
    trigger: true
  - get: snw-concourse-image
    trigger: true
    params:
      skip_download: true
  - put: genesis-ci
    params:
      build: dockerfile/ci
      tag_as_latest: true

