# TODO: docker-image push is insecure, so we must convert to registry-image.
#       However, registry-image push doesn't build, so an additional build task
#       is needed It is recommended by concourse to use oci-build-image, but
#       another system might work better.  See
#       https://github.com/concourse/registry-image-resource#comparison-to-docker-image-resource
#       and https://github.com/concourse/oci-build-task#oci-build-task
#

jobs:
- name: generate-ci-image
  plan:
  - get: ci-dockerfile
    trigger: true
  - get: ci-src-image
    trigger: true
    params:
      skip_download: true
  - put: genesis-ci-image
    get_params: {save: true}
    params:
      build: ci-dockerfile/ci/ci-dockerimage
      tag_as_latest: true
  - put: genesis-ci-dockerhub
    params:
      load: genesis-ci-image
      tag_as_latest: true

