groups:
- (( append ))
- name: renew-token
  jobs:
  - renew-vault-token

resources:
- name: weekly
  type: time
  icon: clock-outline
  source:
    interval: 168h # 1 week

jobs:
- name: renew-vault-token
  public: false
  plan:
  - get: weekly
    trigger: true
  - get: git-ci
    trigger: false
  - task: renew-vault-token
    file: git-ci/ci/tasks/renew-vault-token.yml


